#!/bin/sh
# ~/.config/xinitrc - run on startx

# error file
ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# daemons
picom &
dunst &
nm-applet &
redshift-gtk &

# wallpaper
xwallpaper --zoom ~/.config/wall.png

# pywal theme
wal -Rn &

# auto-repeat
xset r rate 300 50

# start i3wm
i3
